spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@192.168.0.108:27017/flights-service?authSource=admin
  application:
    name: flights-service
  config:
    import: optional:configserver:http://localhost:8888/config
    cloud:
      config:
        enabled: true
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint.health.probes.enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

planes:
  service: PLANES-SERVICE
  path: /api/planes/**