spring:
  application:
    name: api-gateway-server
  config:
    import: optional:configserver:http://localhost:8888/config
    cloud:
      config:
        enabled: true
        uri: http://localhost:8888/config
        label: master
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      metrics:
        enabled: true
      routes:
      - id: planes-service
        uri: lb://planes-service
        predicates:
          - Path=/api/plane
      - id: passengers-service
        uri: lb://passengers-service
        predicates:
          - Path=/api/passenger
      - id: flights-service
        uri: lb://flights-service
        predicates:
          - Path=/api/flight

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint.health.probes.enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  region: default
  registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
