eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    # Preventing server registering itself
  instance:
    hostname: localhost
    health-check-url: /actuator/health
    status-page-url: /actuator/info

server:
  port: 8761

spring:
  application:
    name: discovery
  config:
    import: configserver:http://localhost:8888/config
