spring:
  application:
    name: discovery
  config:
    import: optional:configserver:http://localhost:8888/config
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
      uri: http://localhost:8888/config
      label: master
server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
    # Preventing server registering itself
  instance:
    hostname: localhost
    health-check-url: /actuator/health
    status-page-url: /actuator/info