spring:
  application:
    name: passengers-service
  data:
    mongodb:
      uri: mongodb://admin:admin@192.168.0.108:27017/passengers-service?authSource=admin
  config:
   import: optional:configserver:http://localhost:8888/config
  cloud:
    config:
      enabled: true

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint.health.probes.enabled: true
  endpoints:
    web:
      exposure:
        include: "*"