server:
  port: 8888
  servlet:
    context-path: /config

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint.health.probes.enabled: true

#eureka:
#  client:
#      service-url:
#        defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
          #uri: https://github.com/buildandship/flight-ticket-system
          #search-paths: config-repo*